stages:
    - build
    - package
    - test
variables:
    APP_VERSION: $CI_PIPELINE_ID 


docker build:
     stage: package
     image: docker:20.10.22
     services: 
         
         - docker:20.10.22-dind

     script:
         - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
         - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
         - docker push --all-tags $CI_REGISTRY_IMAGE
         - docker image ls
docker test:
      stage: test
      image: curlimages/curl
      services:
          - name: $CI_REGISTRY_IMAGE:$APP_VERSION
            alias: website

      script:
          - curl http://website/virsion.html | grep $APP_VERSION
